version: '2'
services:
  rabbit:
    hostname: rabbit
    image: rabbitmq
    environment:
        - RABBITMQ_DEFAULT_USER=username
        - RABBITMQ_DEFAULT_PASS=password
    ports:
        - '5673:5672'
        - '15671:15672'
  worker:
    build:
        context: .
        dockerfile: dockerfile
    volumes:
        - .:/app
    links:
        - rabbit
    depends_on:
        - rabbit
  database:
    hostname: mongo
    image: mongo:latest
    ports:
        - "27018:27017"
